services:
  app:
    volumes:
      - .:/var/www/html:cached

  laravel-docker:
    container_name: it-faculty-comlab-scheduler
    build: .
    volumes:
      - "C:/Users/Franz/Desktop/IT-Faculty ComLab Scheduler/comlab_scheduler:/var/www/html"
    ports:
      - "9000:80"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: it_faculty_comlab_schedules
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql_db
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db

volumes:
  mysql_data:


